services:
  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    expose:
      - "80"
    depends_on:
      - frontend
    restart: always
    networks:
      - transcendence-net

  frontend:
    build: ./frontend
    container_name: frontend
    image: frontend:42
    expose:
      - "80"
    depends_on:
      - django
    restart: always
    networks:
      - transcendence-net

  django:
    build: ./django
    container_name: django
    image: django:42
    expose:
      - "8000"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    networks:
      - transcendence-net
      - backend-net

  postgres:
    container_name: postgres
    image: postgres:16.3-bookworm
    volumes:
      - ${SQL_PATH}:/var/lib/postgresql/data/:rw
    expose:
      - "5432"
    env_file:
      - .env
    restart: always
    networks:
      - backend-net

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge
  backend-net:
    name: backend-net
    driver: bridge
    internal: true
